name: Publish to NuGet

on:
  push:
    tags:
      - 'v*'  # Trigger on tags like v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Extract version from tag
        id: get_version
        run: echo "##[set-output name=version;]${GITHUB_REF#refs/tags/v}"

      - name: Restore dependencies
        run: dotnet restore NaturalDateParser/NaturalDateParser.csproj

      - name: Build library
        run: dotnet build NaturalDateParser/NaturalDateParser.csproj --configuration Release --no-restore

      - name: Pack NuGet package
        run: dotnet pack NaturalDateParser/NaturalDateParser.csproj --configuration Release --no-build -p:Version=${{ steps.get_version.outputs.version }}

      - name: Publish to NuGet
        run: dotnet nuget push NaturalDateParser/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate